/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simware_serialchat_SerialPort */

#ifndef _Included_com_obm_mylibrary_SerialPortModel
#define _Included_com_obm_mylibrary_SerialPortModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simware_serialchat_SerialPort
 * Method:    native_open
 * Signature: (Ljava/lang/String;IILjava/lang/String;ILjava/lang/String;)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_obm_mylibrary_SerialPortModel_open
  (JNIEnv *, jclass, jstring, jint, jint, jstring, jint, jstring);

/*
 * Class:     com_simware_serialchat_SerialPort
 * Method:    native_close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_obm_mylibrary_SerialPortModel_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
