/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_simware_qcomgpio_MainActivity */

#ifndef _Included_com_obm_mylibrary_Open
#define _Included_com_obm_mylibrary_Open
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_simware_qcomgpio_MainActivity
 * Method:    nativeSetGPIO
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_obm_mylibrary_Open_nativeSetGPIO
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
